site_title: "Капуцыны ў Беларусі"
site_tagline: "Ордэн Меншых Братоў Капуцынаў"

curia:
  name: "Курыя Кустодыі Ордэна Меншых Братоў Капуцынаў"
  address: "вул. Авіяцыйная 4, Капішча, Мінская вобласць"
  phone: "(8-017) 221-74-08"
  email: "belarus.ofmcap@gmail.com"
  map_embed_url: "" # TODO: вставить embed-ссылку Google Maps

whatsapp_url: "" # TODO: ссылка-запрашэнне ў WhatsApp-групу
facebook_url: "https://facebook.com/sv.francishak"
youtube_url: "https://youtube.com/@kamerton1628"

donate_enabled: false
donate_url: ""

footer_copyright: "© 2026 Беларуская Кустодыя Ордэна Меншых Братоў Капуцынаў"
